{
 "title": "Pi-hole",
 "description": "Pi-hole dashboard for watching 1 or more Pi-hole servers.",
 "tags": [ "pihole" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values(pihole_status,job)"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "query_result(pihole_status{job=~'$JobName'})"
    }
   },
   {
    "name": "QueryTypes",
    "label": "QueryTypes",
    "query": {
     "query": "label_values(pihole_querytypes,type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pi-hole - $Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Device" },
  {
   "title": "Pi-hole Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_status{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Total Queries"
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_dns_queries_today{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Total Queries"
    }
   ]
  },
  {
   "title": "Queries Blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_ads_blocked_today{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Total Queries"
    }
   ]
  },
  {
   "title": "Percent Blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Total Queries"
    }
   ]
  },
  {
   "title": "Domain Blocklist",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Total Queries"
    }
   ]
  },
  {
   "title": "Total queries",
   "type": "graph",
   "description": "Because this graph does a delta between the current and previous 10 minutes it will take 20 minutes before you start seeing data.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(delta(pihole_ads_blocked_today{job=~'$JobName',instance=~'$Device'}[10m]))",
     "legendFormat": "Blocked"
    },
    {
     "expr": "round(delta(pihole_queries_forwarded{job=~'$JobName',instance=~'$Device'}[10m]))",
     "legendFormat": "Permitted"
    }
   ]
  },
  {
   "title": "Client Activity",
   "type": "graph",
   "description": "Because this graph does a delta between the current and previous 10 minutes it will take 20 minutes before you start seeing data.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(delta(pihole_top_sources{job=~'$JobName',instance=~'$Device'}[10m]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "piechart",
   "description": "The types shown here can be limited by updating the QueryTypes variable.  See the description for the variable for an example.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_querytypes{job=~'$JobName',instance=~'$Device',type=~'$QueryTypes'}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queries Answered By",
   "type": "piechart",
   "description": "If you would like to set up or edit the colors you can edit this pane modify the overrides to match your  upstream DNS servers. ",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_forward_destinations{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Top Permitted Domains",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "pihole_top_queries{job=~'$JobName',instance=~'$Device'}"
    }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "pihole_top_ads{job=~'$JobName',instance=~'$Device'}"
    }
   ]
  },
  {
   "title": "Top Clients (total)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "pihole_top_sources{job=~'$JobName',instance=~'$Device'}"
    }
   ]
  }
 ]
}